[phases.setup]
# Comandos executados durante a fase de setup (instalação de dependências, etc.)
commands = [
    "echo 'Configurando o ambiente...'",
    "if ! grep -q '^nobody:' /etc/group; then addgroup nobody; fi",
]

[phases.build]
# Comandos executados durante a fase de build
commands = [
    "echo 'Ajustando permissões...'",
    "chown -R nobody:nobody /app/app/app/database",
    "chmod -R 750 /app/app/app/database",
]


# Manualmente é isso que é feito:
# Verifica se o grupo nobody existe "cat /etc/group | grep nobody" (não imprime nada se não existir)
# Cria o grupo nobody se ele não existir "addgroup nobody"
# Altera o propietário do diretório database "sudo chown -R nobody:nobody /app/app/database"
# Aplica permissões mais restritas "chmod -R 750 /app/app/database"